spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb+srv://user:goorm0508@goorm-mongodb.svz66jf.mongodb.net/?retryWrites=true&w=majority&appName=goorm-mongoDB
      database: content-db

server:
  port: 9007

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://gpadmin:1234@localhost:8761/eureka

# Optional: actuator 등록 (모니터링용)
management:
  endpoints:
    web:
      exposure:
        include: "*"
